//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localisation
    {
        public localisation()
        {
            this.evenement = new HashSet<evenement>();
        }
    
        public int localisation_id { get; set; }
        public string address { get; set; }
        public int cp { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<evenement> evenement { get; set; }
    }
}
