//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.evenement = new HashSet<evenement>();
            this.event_user = new HashSet<event_user>();
            this.user = new HashSet<user>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<evenement> evenement { get; set; }
        public virtual ICollection<event_user> event_user { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
